---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-quarkus-app-dev-build
  namespace: janus-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: janus
  source:
    repoURL: https://gitlab-gitlab.apps.cluster-2g4d5.sandbox92.opentlc.com/development/my-quarkus-app-gitops.git
    targetRevision: HEAD
    path: ./helm/build
  destination:
    server: https://kubernetes.default.svc
    namespace: my-quarkus-app-dev
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name|test(".-dockercfg-."))'
      kind: ServiceAccount
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: -1
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 2m # the maximum amount of time allowed for the backoff strategy
